name: flutter_template
description: Flutter Official Architecture + Feature-First + Riverpod
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  
  # State Management & DI (Riverpod Modern Stack)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  
  # Navigation (Official Recommendation)
  go_router: ^12.1.3
  
  # HTTP Client
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Code Generation & Immutability
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  
  # Mocking (Riverpod compatible)
  mocktail: ^1.0.0
  
  # Code Generation (Riverpod + Freezed)
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # Analysis
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true